image:
  repository: ghcr.io/stealthbadger747/shortslug
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

resources: {}

replicaCount: 1

env:
  SERVER_PORT: "8080"
  FRONTEND_DIR: "/app/static"
  DATABASE_PATH: "/data/shortslug.db"
  SHORTEN_PASSWORD: ""
  CAP_SITEVERIFY_URL: ""
  CAP_SECRET: ""
  CAP_API_ENDPOINT: ""
  BRAND_NAME: "ShortSlug"

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: shortslug.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
